### ISSUE TITLE
Bug: Oneof support does not work with proto2

### ISSUE THREAD

**Issue by Rkiouak** [protojure/protoc-plugin#16]
The current handling of eliding default values when writing out to the wire interacts incorrectly with proto2 semantics.

**Comment by lakshay2395** [comment]
It doesn't work with proto3 semantics either.

**Comment by ghaskins** [comment]
Hi @lakshay2395.  I'm sorry that you are running into trouble.  Could you elaborate on what you are seeing?  I know we use oneof in our production proto3 specifications, so its not clear to me what you are running into.

**Comment by sharrap** [comment]
I'm seeing this issue as well in cases where a sub-message has no fields:

```proto
syntax = "proto3";

package test;

message A {
  int32 i = 1;
}

message E {}

message M {
  oneof oo {
    A a = 1;
    E b = 2;
  }
  int32 c = 3;
}
```

REPL session:

```clj
user=> (require '[protojure.protobuf :as pb] '[test :as t])
nil
user=> (test/pb->M (pb/->pb (test/new-M {:oo {:a {:i 1}} :c 1})))
#test.M-record{:oo {:a #test.A-record{:i 1}}, :c 1}
user=> (test/pb->M (pb/->pb (test/new-M {:oo {:b {}} :c 1})))
#test.M-record{:oo nil, :c 1}
```

**Comment by ghaskins** [comment]
I believe this is fixed with https://github.com/protojure/protoc-plugin/commit/d4025686a3b58fecd02b60d4ca11595d4e7e8522

**Comment by sharrap** [comment]
@ghaskins as far as I understand it this bug (or at least the part I posted about) is actually part of `protojure/lib` and was not fixed by #54.

**Comment by ghaskins** [comment]
@sharrap apologies, that was my misunderstanding.  And yes, moving it over there makes sense to me too.
